# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-erlang"
BBFILE_PATTERN_meta-erlang = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-erlang = "6"

LAYERDEPENDS_meta-erlang = "core"
LAYERSERIES_COMPAT_meta-erlang = "wrynose"
